library(shiny)
library(shinyWidgets)
library(tidyverse)
library(plotly)
library(ggplot2)
library(shinyjs)
library(markdown)
library(maps)

source('www/functions/Part1_single.R')
source('www/functions/Part1_binary1.R')
source('www/functions/Part1_binary2.R')
source('www/functions/Part1_textfunc.R')

source('www/functions/Part2_Data.R')
source('www/functions/Part2_Radarplot.R')
source('www/functions/Part2_Barplot.R')

source('www/functions/Part3_blank.R')
source('www/functions/Part3_singlePart3.R')
source('www/functions/Part3_singlePart3Plot2.R')
